version: "3.9"
services:
  web:
    image: project_api:v1
    container_name: fastapi-app
    ports:
      - "8050:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload